### PR TITLE
added-details-sandra

### PR DESCRIPTION
**Pull request by sjmanyarkiy**
I have added my details to the index.html file and I'd like to merge the changes to the base/main branch

### CODE REVIEW

**Review by Ivy8127 — APPROVED** [review]
LGTM! Good work!

**Review by RuthNjeri — CHANGES_REQUESTED** [review]
Good first attempt @SandraManyarkiy! I believe the image should have dimensions 600pixels by 600 pixels

**Review by sjmanyarkiy — COMMENTED** [review]
I have made the changes to the image. It now fits the dimensions of the other team images on the webpage

**Review by RuthNjeri — APPROVED** [review]
Looks Good To Me!

**Comment by sjmanyarkiy** [comment]
Thanks!

**Review by sjmanyarkiy — COMMENTED** [review]
--

**Pull request merged**
