### PR TITLE
estherwavinya about us

### PR DESCRIPTION
**Pull request by Esther-Wavinya**
My about us details. Created a folder for about us images called aboutus.

### CODE REVIEW

**Comment by muokicaleb** [comment]
Could you resize the image to 600pixels by 600 pixels

**Comment by Esther-Wavinya** [comment]
> Could you resize the image to 600pixels by 600 pixels

I have resized it

**Review by edkariuki — APPROVED** [review]

**Comment by RuthNjeri** [comment]
Good job on your first attempt @Esther-Wavinya! Are the changes in the `style.css` needed? They seem to be related to maybe the editor making the changes when you save the file?

**Comment by Esther-Wavinya** [comment]
> Good job on your first attempt @Esther-Wavinya! Are the changes in the `style.css` needed? They seem to be related to maybe the editor making the changes when you save the file?

I did not make any changes in the style.css file

**Comment by RuthNjeri** [comment]
> > Good job on your first attempt @Esther-Wavinya! Are the changes in the `style.css` needed? They seem to be related to maybe the editor making the changes when you save the file?
> 
> I did not make any changes in the style.css file

Try and remove them, you can look into reverting a specific file to it's original with master, have a look at this link https://stackoverflow.com/questions/37972753/git-reset-single-file-in-feature-branch-to-be-the-same-as-in-master

Also, try and find out if there is a setting in your Editor that autocorrects CSS files and turn it off.

**Comment by RuthNjeri** [comment]
Hi Esther, did you have a look at this?

> > > Good job on your first attempt @Esther-Wavinya! Are the changes in the `style.css` needed? They seem to be related to maybe the editor making the changes when you save the file?
> > 
> > 
> > I did not make any changes in the style.css file
> 
> Try and remove them, you can look into reverting a specific file to it's original with master, have a look at this link https://stackoverflow.com/questions/37972753/git-reset-single-file-in-feature-branch-to-be-the-same-as-in-master
> 
> Also, try and find out if there is a setting in your Editor that autocorrects CSS files and turn it off.

**Comment by Esther-Wavinya** [comment]
Hey

I checked. But I was unable to resolve. I wonder why it says I changes and
yet I didn't make any changes.

**Comment by RuthNjeri** [comment]
Hi @Esther-Wavinya, you can look into this option https://stackoverflow.com/questions/37972753/git-reset-single-file-in-feature-branch-to-be-the-same-as-in-master

let me know if it helps, you can use it for files that you did not intend to change.

**Comment by RuthNjeri** [comment]
Feedback implementation took too long. Closing the PR.

**Pull request closed without merging**
