### PR TITLE
Irungu's Edit

### PR DESCRIPTION
**Pull request by irungudeveloper**
This is a pull request for the edits I have made on the index.html file of the project

### CODE REVIEW

**Review by sjmanyarkiy — APPROVED** [review]
since the branch will not conflict with the base branch, you may go ahead and pull - Sandra

**Comment by muokicaleb** [comment]
Could you add you photo and social links section.

**Comment by RuthNjeri** [comment]
> since the branch will not conflict with the base branch, you may go ahead and pull - Sandra

I think once this PR is merged, it will be difficult to pull Sandra, plus, won't the changes in the branch `Sandra` need to be merged?

@irungudeveloper good first attempt with the forking, branching, committing and creating the PR. There is additional feedback Muoki has shared in a comment above, you can do this in another commit. Let us know if you need any help.

**Comment by irungudeveloper** [comment]
I have implemented the changes on a newer pull request

**Pull request closed without merging**
